version: '3'

services:
  proxy:
    image: "serjs/go-socks5-proxy"
    container_name: quassel_proxy
    depends_on:
      - core
    network:
      - public
      - quassel_net
    labels:
      - "traefik.backend=ircQuassel"
      - "traefik.frontend.rule=Host:"
      - "traefik.enable=true"
      - "traefik.port=1080"
#      - "traefik.frontend.auth.basic=[]"

  core:
    build: ./quassel
    container_name: quassel_core
    network:
      - quassel_net
    volumes:
      - "/srv/quassel:/var/lib/quassel"

networks:
  quassel_net:
    driver: bridge
  public:
    external:
      name: traefik_net
